Feature/lending
CODEBASE-Okinawa/codebase_books_power pull request #16
Opened 2023-02-18 03:27 UTC by hayato-f

## lendingsのindexページと、機能の追加
- `lendings`コントローラー、`index`、`show`アクションの追加
- `lendings`のルーティング追加
- ユーザーが貸出中の本を`lendings#index`に表示する機能の追加

2023-02-18 07:19 UTC, osatoh requested changes
コメントしたので確認よろしくお願いします 🙏

2023-02-18 07:19 UTC, osatoh commented on app/models/user.rb
> +  end
`current_user.lendings`で取得できそうですけど、いかがでしょうか！

2023-02-18 07:19 UTC, osatoh commented on app/models/lending.rb
> +  scope :return_false, -> { where(return_status: false) }
`return_false`だと「falseを返す」メソッドに見えちゃいそうです 👀 
個人的には`not_yet_returned`とかがいいかなと思います 🚃

2023-02-18 07:19 UTC, osatoh commented on app/views/lendings/index.html.erb
> +<% end %>
インデントがとんでもないことに 😂

2023-02-18 07:19 UTC, osatoh commented on app/controllers/lendings_controller.rb
> +  before_action :require_signed_in, only: [:index, :show]
下1行開けたいかもです 🙏

2023-02-18 07:19 UTC, osatoh commented on config/routes.rb
> +  get 'lendings/show', to: 'lendings#show'
`resources`でまとめたいですね！

2023-02-18 07:36 UTC, hayato-f commented on app/views/lendings/index.html.erb
> +<% end %>
@osatoh 
インデントとは、13,14行目のことでしょうか？

2023-02-19 04:36 UTC, osatoh commented on app/views/lendings/index.html.erb
> +  <% @lendings.each do |lend| %>
lendingでもいいかもですね！

2023-02-19 04:37 UTC, osatoh approved these changes
LGTM！

2023-02-19 04:37 UTC, merged