予約詳細の画面を修正
CODEBASE-Okinawa/codebase_books_power pull request #26
Opened 2023-02-20 12:01 UTC by yukimugikura

- 予約詳細画面の表示内容を修正
- 予約一覧から予約した本への詳細のリンク修正

2023-02-20 12:58 UTC, osatoh requested changes

2023-02-20 12:58 UTC, osatoh commented on app/controllers/books_controller.rb
> +  end
スペース消したいかもです 🙏

2023-02-20 12:58 UTC, osatoh commented on app/controllers/reservations_controller.rb
> +    redirect_to book_path(@@reserved_book.book.id)
【純粋な質問】@が2個になってるかもですけど、こういう記法があったり、、？ 👀 
`book_path(@reserved_book)`で行けるかもなので試してみてください 🙌

2023-02-20 12:58 UTC, osatoh commented on app/views/reservations/index.html.erb
> +    <% end %>
```rb
@reservations.each do |reservation|
  reservation.book.title
end
```
が重複なくて綺麗かなと思うのですがいかがでしょう？(提案)

2023-02-20 14:27 UTC, yukimugikura commented on app/controllers/reservations_controller.rb
> +    redirect_to book_path(@@reserved_book.book.id)
@はタイプミスです
book_path(@reserved_book)　だと　reservationのid が渡されて、別の本のshowにredirect されてしまうかもです。

2023-02-20 14:48 UTC, yukimugikura commented
reservation controllerのindeとshowの中にあるインスタンス変数名を変更
index: reserved_books →reservations
show: reserved_book →reservation 

それに伴い各erb内の変数名も修正

2023-02-21 09:27 UTC, osatoh commented on app/views/reservations/show.html.erb
> +<p><%= @reservation.reservation_at%> ~ <%= @reservation.return_at %></p>
DB設計の段階の話ですが、reservation_atじゃなくて、reserved_atだったかもですね 😂

2023-02-21 09:27 UTC, osatoh commented on app/controllers/reservations_controller.rb
> +    redirect_to book_path(@reservation.book.id)
```suggestion
    redirect_to book_path(@reservation.book)
```
で行けたりします、、？ 👀

2023-02-21 09:27 UTC, osatoh commented on app/controllers/reservations_controller.rb
> +    # redirect_to login_url, status: :see_other
このコメントアウト消してもいいかもです 🙏

2023-02-21 09:27 UTC, osatoh commented on app/controllers/reservations_controller.rb
> +    redirect_to book_path(@reservation.book.id)
```suggestion
    redirect_to book_path(@reservation.book)
```
で行けたりします、、？ 👀

2023-02-21 09:27 UTC, osatoh commented on app/controllers/reservations_controller.rb
> +    redirect_to book_path(@reservation.book.id)
```suggestion
    redirect_to book_path(@reservation.book) unless @reservation
```
にまとめてもいいかもです 🤔 

読みにくければ、`@reservation.book.id`の`id`だけ消してもらえると 🙏

2023-02-21 10:26 UTC, osatoh approved these changes

2023-02-21 10:26 UTC, merged