admin/本の登録機能の追加
CODEBASE-Okinawa/codebase_books_power pull request #27
Opened 2023-02-20 12:35 UTC by hayato-f

## アドミンユーザーが本の登録をできる機能
- admin/books
  - new,createルーティングの追加 
  - new,createアクションの追加
  - newのviewファイルを追加
- 画像の登録
  - アクティブストレージを追加
  - admin,books,lendingsのindexのviewファイルを編集

2023-02-20 13:05 UTC, osatoh requested changes

2023-02-20 13:05 UTC, osatoh commented on app/controllers/admin/books_controller.rb
> +    # debugger
これは消しましょう！

2023-02-20 13:05 UTC, osatoh commented on app/controllers/admin/books_controller.rb
> +    @book.image.attach(params[:book][:image])
せっかくstrong_parameter定義してるのでそっち使ってみても、、？

2023-02-20 13:05 UTC, osatoh commented on app/controllers/admin/books_controller.rb
> +    # debugger
消しましょう！

2023-02-20 13:05 UTC, osatoh commented on app/models/book.rb
> +  validates :title, presence: true
これ消しちゃって大丈夫です！

2023-02-20 13:05 UTC, osatoh commented on app/views/admin/books/index.html.erb
> +      <%= image_tag 'sample.jpeg', size: 200 %>
no imageですかね？
チェリー本の画像とかだと避けたいかもです 🤔

2023-02-20 13:05 UTC, osatoh commented on app/views/admin/books/new.html.erb
> +    <%= f.submit "本を登録する" %>
インデントはスペース2つでいきましょう 🙌

2023-02-20 13:05 UTC, osatoh commented on app/views/books/index.html.erb
> +        <%= image_tag 'sample.jpeg', size: 200 %>
no imageですかね？
チェリー本の画像とかだと避けたいかもです 🤔

2023-02-20 13:05 UTC, osatoh commented on app/views/lendings/index.html.erb
> +          <%= link_to (image_tag 'sample.jpeg', size: 200), lending_path(lend) %>
no imageですかね？
チェリー本の画像とかだと避けたいかもです 🤔

2023-02-20 13:05 UTC, osatoh commented on app/views/lendings/index.html.erb
> +        <%#= link_to lend.book.title, lending_path(lend) %>
これは消しちゃいましょう 👍

2023-02-20 13:05 UTC, osatoh commented on app/views/lendings/show.html.erb
> +      <%= image_tag 'sample.jpeg', size: 500 %>
no imageですかね？
チェリー本の画像とかだと避けたいかもです 🤔

2023-02-20 13:39 UTC, hayato-f commented on app/controllers/admin/books_controller.rb
> +    @book.image.attach(params[:book][:image])
strong_parameterを使うと、image取得できなくなります💦
チュートリアルでも、strong_parameter使わずに同様の書き方してるので、他に方法がない気がしてます...

2023-02-20 13:41 UTC, hayato-f commented on app/models/book.rb
> +  validates :title, presence: true
4,5行のコード消すと、画像が追加できなくなります💦
何か別の書き方をする必要があるのでしょうか？

2023-02-21 02:49 UTC, osatoh commented on app/controllers/admin/books_controller.rb
> +    @book.image.attach(params[:book][:image])
なるほど！
ならそのままでお願いします 🙇

2023-02-21 02:49 UTC, osatoh commented on app/models/book.rb
> +  validates :title, presence: true
消すのは5行目だけです！
前自分が追加して、消したと思うのですが、いらないのでここで消しちゃってください 🙇 
わかりにくくてすみません 🙇

2023-02-21 09:37 UTC, osatoh reviewed
LGTM!

2023-02-21 09:37 UTC, osatoh approved these changes

2023-02-21 09:37 UTC, merged