fix books status
CODEBASE-Okinawa/codebase_books_power pull request #70
Opened 2023-02-25 14:39 UTC by yukimugikura

Controller indexを修正。ログインしていなくても本一覧を表示
ステータス表示のN+1問題を修正。

2023-02-25 16:26 UTC, osatoh requested changes

2023-02-25 16:26 UTC, osatoh commented on app/controllers/books_controller.rb
> +  before_action :logged_in_user, only: %i[show]
```suggestion
  before_action :redirect_to_sign_in, only: %i[show], unless: :user_signed_in?
```
application_controllerで `redirect_to_sign_in` を定義してるので確認してみてください 🙏

2023-02-25 16:26 UTC, osatoh commented on app/controllers/books_controller.rb
> +    redirect_to new_user_session_path, status: :see_other
ここ消しちゃって良さそうです 🙏

2023-02-25 16:26 UTC, osatoh commented on app/helpers/books_helper.rb
> +  # end
実装済んでるなら削除して良さそうです 💪

2023-02-25 16:26 UTC, osatoh commented on app/controllers/books_controller.rb
> +  end
```suggestion
  def status
    user_id = current_user&.id
    lending_status = lend_active.any?{ |lending| lending.user_id == current_user_id }
    reservation_status = reservation_active.any?{ |reservation| reservation.user_id == current_user_id }

    if lending_status && user_id.present?
      "lending"
    elsif reservation_status && user_id.present?
      "reserved"
    elsif lend_active.present?
      "lent"
    else
      "available"
    end
  end
```
Bookモデルに上記のように定義しても良さそうです 💪 
viewにも追記してます 👍

2023-02-25 16:26 UTC, osatoh commented on app/views/books/index.html.erb
> +          <% end %>
```suggestion
          <% if book.status == "lending" %>
            <span class="text-sm text-black" style = "background:#0096FF;font-weight:bold;">現在借りています</span>
          <% elsif book.status == "reserved" %>
            <span class="text-sm text-black" style = "background:#FFEE75;font-weight:bold;">予約しています</span>
          <% elsif book.status == "lent" %>
            <span class="text-sm text-black" style = "background:#FF2c2c;font-weight:bold;">貸出中</span>
          <% else %>
            <span class="text-sm text-black" style = "background:#98FF98;font-weight:bold;">貸出可能</span>
          <% end %>
```
上のstatusメソッドを踏まえるとerbはこんな感じになりそうです 🤔

2023-02-25 16:39 UTC, osatoh reviewed
books_controller#indexも
```rb
    @books = Book.eager_load(:reservation_active, :lend_active).with_attached_image
```
と書くとさらに良さそうです 🙏

2023-02-26 01:51 UTC, osatoh approved these changes

2023-02-26 01:51 UTC, merged

2023-02-27 08:13 UTC, saboyutaka commented
@yukimugikura これはめちゃくちゃいいPR 🤝